#!/bin/bash -

set -x
fn=$(basename "$0")

function _run_sota() {
    indset='--split 10 --inductive'
	time python3 -u main.pyc JKNet chameleon $@ $indset --n-layers 4
	time python3 -u main.pyc JKNet squirrel $@ $indset --n-layers 8
	time python3 -u main.pyc GCNII flickr $@ $indset --n-layers 2 --alpha 0.1 --theta 0.5
	time python3 -u main.pyc GCNII pubmed $@ $indset --n-layers 8 --alpha 0.1 --theta 1.0
	time python3 -u main.pyc GAT corafull $@ $indset --heads 8
	time python3 -u main.pyc GCNII amazon-photo $@ $indset --n-layers 4 --alpha 0.1 --theta 0.5
	time python3 -u main.pyc JKNet amazon-com $@ $indset --n-layers 2
	time python3 -u main.pyc GCNII coauthor-cs $@ $indset --n-layers 8 --alpha 0.5 --theta 0.5
	time python3 -u main.pyc GCNII coauthor-phy $@ $indset --n-layers 8 --alpha 0.3 --theta 1.5
    time python3 -u main.pyc GCNII arxiv $@ --n-layers 4 --alpha 0.1 --theta 0.5 --hidden 256
}

function _run() {
    # SotA + C&S
    for cr in 0.1 0.2 0.3; do
        for sr in 0.1 0.2 0.3; do
            _run_sota $@ --correct 50 --correct-rate $cr --smooth 50 --smooth-rate $sr
        done
    done

    # L-SotA
    for mask in 0.25 0.5 0.75; do
        for reuse in 0 1 3; do
            _run_sota $@ --input-label $mask --for-iter $reuse
        done
    done

    # LI-SotA
    for mask in 0.25 0.5 0.75; do
        _run_sota $@ --input-label 1 --for-iter 10 --back-iter 10 --drop-state $mask
    done
}

_run --runs 10 | tee -a logs/$fn.log
