#!/bin/bash -

set -x
fn=$(basename "$0")

# args="--runs 10 --split 10 --inductive"
# for dataset in chameleon squirrel amazon-photo; do
#     # EIGNN
# 	time python3 -u main.pyc EIGNN $dataset $args 2>&1
# done | tee -a logs/$fn.log

args="--runs 10 --split 10 --inductive"
for dataset in chameleon squirrel flickr pubmed corafull amazon-photo amazon-com coauthor-cs coauthor-phy arxiv; do
    # MLP
    time python3 -u main_induc_ignn.pyc MLP $dataset $args --n-layers 3 2>&1
    # GAT
    for heads in 2 4 8; do
        time python3 -u main_induc_ignn.pyc GAT $dataset $args --heads $heads 2>&1
    done
    for layers in 2 4 8; do
        # JKNet
        time python3 -u main_induc_ignn.pyc JKNet $dataset $args --n-layers $layers 2>&1
        # GCNII
        for alpha in 0.1 0.3 0.5; do
            for theta in 0.5 1 1.5; do
                time python3 -u main_induc_ignn.pyc GCNII $dataset $args --n-layers $layers --alpha $alpha --theta $theta 2>&1
            done
        done
    done
    # IGNN
	time python3 -u main_induc_ignn.pyc IGNN $dataset $args 2>&1
done | tee -a logs/$fn.log

date
