#!/bin/bash -

set -x
args="--gpu 0 --runs 10"

for dataset in chain-10 weekday chameleon squirrel amazon-photo coauthor-cs; do
    time python3 -u main.pyc GCN $dataset $args 2>&1
    time python3 -u main.pyc GCN $dataset $args --label-input 0.5 2>&1
    time python3 -u main.pyc GCN $dataset $args --dropout 0.5 2>&1
    time python3 -u main.pyc GCN $dataset $args --weight-decay 0.0005 2>&1
    time python3 -u main.pyc GQN $dataset $args --noise 1 2>&1
    time python3 -u main.pyc GQN $dataset $args --drop-state 0.5 2>&1

    time python3 -u main.pyc GQN $dataset $args --skip-connection 2>&1
    time python3 -u main.pyc GQN $dataset $args --skip-connection --label-input 0.5 2>&1
    time python3 -u main.pyc GQN $dataset $args --skip-connection --dropout 0.5 2>&1
    time python3 -u main.pyc GQN $dataset $args --skip-connection --weight-decay 0.0005 2>&1
    time python3 -u main.pyc GQN $dataset $args --skip-connection --noise 1 2>&1
    time python3 -u main.pyc GQN $dataset $args --skip-connection --drop-state 0.5 2>&1
done | tee -a logs/$0.log
date
