#!/bin/bash -

set -x
fn=$(basename "$0")
args="--runs 10 --input-label 1 --for-iter 300 --max-epochs 200 --early-stop-epochs 200"

for dataset in cora citeseer chameleon wisconsin; do
    for mask in 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 0.95 0.97 0.98 0.99; do
        time python3 -u main.py GCN $dataset $args --drop-state $mask
        time python3 -u main.py GCN $dataset $args --drop-state $mask --back-iter 300
    done
done | tee -a logs/$fn.log
date
