#!/bin/bash -

set -x
gpu=0
runs=10

for dataset in weekday; do
    # GCN
    time python3 -u main.pyc GCN $dataset --gpu $gpu --runs $runs 2>&1
    time python3 -u main.pyc GCN $dataset --gpu $gpu --runs $runs --skip-connection 2>&1

    # C&S
    time python3 -u main.pyc MLP $dataset --gpu $gpu --runs $runs --correct 50 --correct-rate 0.1 --smooth 50 --smooth-rate 0.1 2>&1
    # Label Input & Label Reuse
    for reuse in 0 1; do
        time python3 -u main.pyc GCN $dataset --gpu $gpu --runs $runs --label-input 0.5 --label-reuse $reuse 2>&1
    done

    # IGNN
    time python3 -u main.pyc IGNN $dataset --gpu $gpu --runs $runs 2>&1
    # EIGNN
    time python3 -u main.pyc EIGNN $dataset --gpu $gpu --runs $runs 2>&1
    # GQN
    time python3 -u main.pyc GQN $dataset --gpu $gpu --runs $runs --label-input 0.5 2>&1
    time python3 -u main.pyc GQN $dataset --gpu $gpu --runs $runs --skip-connection --label-input 0.5 2>&1
done | tee -a logs/$0.log
date
