#!/bin/bash -

set -x
fn=$(basename "$0")

function _run_gcn() {
    for dataset in chameleon squirrel pubmed corafull flickr amazon-photo amazon-com coauthor-phy coauthor-cs; do
        time python3 -u main.pyc GCN $dataset $@ --split 10 --inductive
    done
    for dataset in arxiv; do
        time python3 -u main.pyc GCN $dataset $@ --hidden 256
    done
}

function _run() {
    # GCN
    _run_gcn $@

    # GCN + C&S
    for cr in 0.1 0.2 0.3; do
        for sr in 0.1 0.2 0.3; do
            _run_gcn $@ --correct 50 --correct-rate $cr --smooth 50 --smooth-rate $sr
        done
    done

    # L-GCN
    for mask in 0.25 0.5 0.75; do
        for reuse in 0 1 3; do
            _run_gcn $@ --input-label $mask --for-iter $reuse
        done
    done

    # LI-GCN
    for mask in 0.25 0.5 0.75; do
        _run_gcn $@ --input-label 1 --for-iter 10 --back-iter 10 --drop-state $mask
    done
}

_run --runs 10 | tee -a logs/$fn.log

date
