#!/bin/bash -

set -x
fn=$(basename "$0")
args="--runs 1"

for dataset in weekday; do
    # GCN
    time python3 -u main.pyc GCN $dataset $args 2>&1
    # GAT
    for heads in 2 8 32; do
        time python3 -u main.pyc GAT $dataset $args --heads $heads 2>&1
    done
    # IGNN
    time python3 -u main.pyc IGNN $dataset $args 2>&1
    # EIGNN
    time python3 -u main.pyc EIGNN $dataset $args 2>&1
    # C&S
    for cr in 0.1 0.2 0.3; do
        for sr in 0.1 0.2 0.3; do
            time python3 -u main.pyc MLP $dataset $args --n-layers 3 --correct 50 --correct-rate $cr --smooth 50 --smooth-rate $sr 2>&1
        done
    done
    # Label Input & Label Reuse
    for mask in 0.25 0.5 0.75; do
        for reuse in 0 1 3; do
            time python3 -u main.pyc GCN $dataset $args --input-label $mask --for-iter $reuse 2>&1
        done
    done
    # LI-GNN
    time python3 -u main.pyc GCN $dataset $args --input-label 1 --for-iter 100 --back-iter 100 --drop-state 1 2>&1
done | tee -a logs/$fn.log
date
